### ISSUE TITLE
Error java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by rentouw** [rentouw/Manga-Downloader#8]
**Describe the bug**
When he wants to acces the Spider classes he crashes.

**To Reproduce**
1. Select download with a filled manga.list file.
OR
1. Add a new manga
2. Select download yes

**Expected behavior**
It should just print the urls it finds on the page.

**Desktop (please complete the following information):**
 - OS: 4.19.91-1-MANJARO  x86_64 GNU/Linux

**Additional context**
The error report is this.

> Exception in thread "main" java.lang.NoClassDefFoundError: org/jsoup/Jsoup
	   at com.rentouw.SpiderLeg.crawl(SpiderLeg.java:27)
	   at com.rentouw.Spider.search(Spider.java:31)
	   at com.rentouw.Download.testUrl(Download.java:97)
	   at com.rentouw.Utils.add(Utils.java:60)
	   at com.rentouw.Main.main(Main.java:74)
Caused by: java.lang.ClassNotFoundException: org.jsoup.Jsoup
	   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	.   .. 5 more

**Comment by rentouw** [comment]
Fixed by adding 
```gradle
jar {
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    manifest {
        attributes 'Main-Class': 'com.rentouw.Main'
    }
} 
```
To build.gradle
